import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import Provider from '@/components/Providers';
import { ThemeProvider } from '@/components/shared/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Provider>
      <html lang='en' suppressHydrationWarning={true}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <div className='fixed h-screen w-full ' />
          <body className={inter.className}>
            <Header />
            <main className='relative z-10'>{children}</main>
          </body>
        </ThemeProvider>
      </html>
    </Provider>
  );
}
